name: Node build
run-name: Build nodejs app
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4
      - name: Usar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Instalar dependencias
        working-directory: ./libroLog
        run: |
          npm install
      - name: Compilar
        working-directory: ./libroLog
        run: |
          npm run build