name: Node CI Pipeline
run-name: CI nodejs app

on: [push]

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4

      - name: Usar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instalar dependencias
        working-directory: ./libroLog
        run: |
          npm install

      - name: Compilar
        working-directory: ./libroLog
        run: |
          npm run build

  lint:
    name: Lint
    runs-on: self-hosted
    needs: build
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4

      - name: Usar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instalar dependencias
        working-directory: ./libroLog
        run: |
          npm install

      - name: Ejecutar lint
        working-directory: ./libroLog
        run: |
          npm run lint

  test:
    name: Test
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4

      - name: Usar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instalar dependencias
        working-directory: ./libroLog
        run: |
          npm install

      - name: Ejecutar tests
        working-directory: ./libroLog
        run: |
          npm run test
