name: Node Lint
run-name: Lint nodejs app
on: [push]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4

      - name: Usar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instalar dependencias
        working-directory: ./libroLog
        run: |
          npm install

      - name: Ejecutar lint
        working-directory: ./libroLog
        run: |
          npm run lint